import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";





export const metadata: Metadata = {
  title: "Parallel",
  description: "Generated by create next app",
};

export default function AnaliticsRootLayout({
  children,
  Analytics,
  Blog,
}: Readonly<{
  children: React.ReactNode;
  Analytics: any;
  Blog: any;
}>) {
  return (
    <>
    
     <div style={{border:"1px solid #000", height:"40vh", width:"100%"}}> {children}</div>
    <div style={{display:"flex", gap:"20px", padding:"20px"}}>  <div style={{border:"1px solid #000", height:"40vh", width:"100%"}}>  {Analytics}</div><div style={{border:"1px solid #000",  width:"100%"}}> {Blog}</div></div>
     
    </>
  );
}
